name: SocialTags Gem CI

on:
  push:
    paths:
      - "gems/social_tags/**"

defaults:
  run:
    working-directory: gems/social_tags/

jobs:

  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.1.2"

    steps:

      - name: Checkout latest changes
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: gems/social_tags/
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run the default task
        run: bundle exec rake
